/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i acesscontrol/acesscontrolmanager.h -c AcessControlAdaptor -l AcessControlManager -a dbusadaptor/acesscontrol_adaptor acesscontrol.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/acesscontrol_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AcessControlAdaptor
 */

AcessControlAdaptor::AcessControlAdaptor(AcessControlManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AcessControlAdaptor::~AcessControlAdaptor()
{
    // destructor
}

bool AcessControlAdaptor::acquireFullAuthentication(const QString &userName, const QString &path)
{
    // handle method call com.deepin.filemanager.daemon.AcessControlManager.acquireFullAuthentication
    return parent()->acquireFullAuthentication(userName, path);
}

