/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i commandmanager/commandmanager.h -c CommandManagerAdaptor -l CommandManager -a dbusadaptor/commandmanager_adaptor commandmanager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/commandmanager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CommandManagerAdaptor
 */

CommandManagerAdaptor::CommandManagerAdaptor(CommandManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CommandManagerAdaptor::~CommandManagerAdaptor()
{
    // destructor
}

bool CommandManagerAdaptor::process(const QString &cmd, const QStringList &args, QString &output, QString &error)
{
    // handle method call com.deepin.filemanager.daemon.CommandManager.process
    return parent()->process(cmd, args, output, error);
}

bool CommandManagerAdaptor::startDetached(const QString &cmd, const QStringList &args)
{
    // handle method call com.deepin.filemanager.daemon.CommandManager.startDetached
    return parent()->startDetached(cmd, args);
}

