/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i deviceinfo/deviceinfomanager.h -c DeviceInfoManagerAdaptor -l DeviceInfoManager -a dbusadaptor/deviceinfomanager_adaptor deviceinfo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/deviceinfomanager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceInfoManagerAdaptor
 */

DeviceInfoManagerAdaptor::DeviceInfoManagerAdaptor(DeviceInfoManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceInfoManagerAdaptor::~DeviceInfoManagerAdaptor()
{
    // destructor
}

PartMan::Partition DeviceInfoManagerAdaptor::getPartitionByDevicePath(const QString &devicePath)
{
    // handle method call com.deepin.filemanager.daemon.DeviceInfoManager.getPartitionByDevicePath
    return parent()->getPartitionByDevicePath(devicePath);
}

bool DeviceInfoManagerAdaptor::readUsage(const QString &path, qlonglong &freespace, qlonglong &total)
{
    // handle method call com.deepin.filemanager.daemon.DeviceInfoManager.readUsage
    return parent()->readUsage(path, freespace, total);
}

