/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../disk/diskmanager.h -c DiskAdaptor -l DiskManager -a ./dbusadaptor/disk_adaptor disk.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dbusadaptor/disk_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DiskAdaptor
 */

DiskAdaptor::DiskAdaptor(DiskManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DiskAdaptor::~DiskAdaptor()
{
    // destructor
}

void DiskAdaptor::changeDiskPassword(const QString &oldPwd, const QString &newPwd)
{
    // handle method call com.deepin.filemanager.daemon.DiskManager.changeDiskPassword
    parent()->changeDiskPassword(oldPwd, newPwd);
}

