/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i quicksearch/quicksearchdaemon.h -c QuickSearchDaemonAdaptor -a dbusadaptor/quicksearchdaemon_adaptor quicksearchdaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QUICKSEARCHDAEMON_ADAPTOR_H
#define QUICKSEARCHDAEMON_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "quicksearch/quicksearchdaemon.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.daemon.QuickSearchDaemon
 */
class QuickSearchDaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.daemon.QuickSearchDaemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.daemon.QuickSearchDaemon\">\n"
"    <method name=\"search\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"current_dir\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"key_words\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"result\"/>\n"
"    </method>\n"
"    <signal name=\"filesWereDeleted\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"files_path\"/>\n"
"    </signal>\n"
"    <signal name=\"filesWereRenamed\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"old_and_new\"/>\n"
"    </signal>\n"
"    <signal name=\"filesWereCreated\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"files_path\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    QuickSearchDaemonAdaptor(QObject *parent);
    virtual ~QuickSearchDaemonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusVariant search(const QDBusVariant &current_dir, const QDBusVariant &key_words);
Q_SIGNALS: // SIGNALS
    void filesWereCreated(const QDBusVariant &files_path);
    void filesWereDeleted(const QDBusVariant &files_path);
    void filesWereRenamed(const QVariantMap &old_and_new);
};

#endif
