/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i quicksearch/quicksearchdaemon.h -c QuickSearchDaemonAdaptor -a dbusadaptor/quicksearchdaemon_adaptor quicksearchdaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QUICKSEARCHDAEMON_ADAPTOR_H
#define QUICKSEARCHDAEMON_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "quicksearch/quicksearchdaemon.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.daemon.QuickSearchDaemon
 */
class QuickSearchDaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.daemon.QuickSearchDaemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.daemon.QuickSearchDaemon\">\n"
"    <method name=\"search\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"current_dir\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"key_words\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"createCache\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"whetherCacheCompletely\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"fileWereCreated\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"file_list\"/>\n"
"    </method>\n"
"    <method name=\"fileWereDeleted\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"file_list\"/>\n"
"    </method>\n"
"    <method name=\"fileWereRenamed\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"old_and_new\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QuickSearchDaemonAdaptor(QObject *parent);
    virtual ~QuickSearchDaemonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusVariant createCache();
    void fileWereCreated(const QDBusVariant &file_list);
    void fileWereDeleted(const QDBusVariant &file_list);
    void fileWereRenamed(const QDBusVariant &old_and_new);
    QDBusVariant search(const QDBusVariant &current_dir, const QDBusVariant &key_words);
    QDBusVariant whetherCacheCompletely();
Q_SIGNALS: // SIGNALS
};

#endif
