/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i tag/tagmanagerdaemon.h -c TagManagerDaemonAdaptor -a dbusadaptor/tagmanagerdaemon_adaptor tagmanagerdaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/tagmanagerdaemon_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TagManagerDaemonAdaptor
 */

TagManagerDaemonAdaptor::TagManagerDaemonAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TagManagerDaemonAdaptor::~TagManagerDaemonAdaptor()
{
    // destructor
}

QDBusVariant TagManagerDaemonAdaptor::disposeClientData(const QVariantMap &filesAndTags, qulonglong type)
{
    // handle method call com.deepin.filemanager.daemon.TagManagerDaemon.disposeClientData
    QDBusVariant result;
    QMetaObject::invokeMethod(parent(), "disposeClientData", Q_RETURN_ARG(QDBusVariant, result), Q_ARG(QVariantMap, filesAndTags), Q_ARG(qulonglong, type));
    return result;
}

