/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i tag/tagmanagerdaemon.h -c TagManagerDaemonAdaptor -l TagManagerDaemon -a dbusadaptor/tagmanagerdaemon_adaptor tagmanagerdaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/tagmanagerdaemon_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TagManagerDaemonAdaptor
 */

TagManagerDaemonAdaptor::TagManagerDaemonAdaptor(TagManagerDaemon *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TagManagerDaemonAdaptor::~TagManagerDaemonAdaptor()
{
    // destructor
}

QDBusVariant TagManagerDaemonAdaptor::disposeClientData(const QVariantMap &filesAndTags, const QString &userName, qulonglong type)
{
    // handle method call com.deepin.filemanager.daemon.TagManagerDaemon.disposeClientData
    return parent()->disposeClientData(filesAndTags, userName, type);
}

void TagManagerDaemonAdaptor::lockBackend()
{
    // handle method call com.deepin.filemanager.daemon.TagManagerDaemon.lockBackend
    parent()->lockBackend();
}

void TagManagerDaemonAdaptor::unlockBackend()
{
    // handle method call com.deepin.filemanager.daemon.TagManagerDaemon.unlockBackend
    parent()->unlockBackend();
}

