/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i usbformatter/usbformatter.h -c UsbFormatterAdaptor -l UsbFormatter -a dbusadaptor/usbformatter_adaptor usbformatter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/usbformatter_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UsbFormatterAdaptor
 */

UsbFormatterAdaptor::UsbFormatterAdaptor(UsbFormatter *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UsbFormatterAdaptor::~UsbFormatterAdaptor()
{
    // destructor
}

bool UsbFormatterAdaptor::mkfs(const QString &path, const QString &fstype, const QString &label)
{
    // handle method call com.deepin.filemanager.daemon.UsbFormatter.mkfs
    return parent()->mkfs(path, fstype, label);
}

