/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i usbformatter/usbformatter.h -c UsbFormatterAdaptor -l UsbFormatter -a dbusadaptor/usbformatter_adaptor usbformatter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef USBFORMATTER_ADAPTOR_H
#define USBFORMATTER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "usbformatter/usbformatter.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.daemon.UsbFormatter
 */
class UsbFormatterAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.daemon.UsbFormatter")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.daemon.UsbFormatter\">\n"
"    <method name=\"mkfs\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"fstype\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"label\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    UsbFormatterAdaptor(UsbFormatter *parent);
    virtual ~UsbFormatterAdaptor();

    inline UsbFormatter *parent() const
    { return static_cast<UsbFormatter *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool mkfs(const QString &path, const QString &fstype, const QString &label);
Q_SIGNALS: // SIGNALS
};

#endif
