/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i usershare/usersharemanager.h -c UserShareAdaptor -l UserShareManager -a dbusadaptor/usershare_adaptor usershare.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/usershare_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UserShareAdaptor
 */

UserShareAdaptor::UserShareAdaptor(UserShareManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UserShareAdaptor::~UserShareAdaptor()
{
    // destructor
}

bool UserShareAdaptor::addGroup(const QString &groupName)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.addGroup
    return parent()->addGroup(groupName);
}

bool UserShareAdaptor::addUserToGroup(const QString &userName, const QString &groupName)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.addUserToGroup
    return parent()->addUserToGroup(userName, groupName);
}

bool UserShareAdaptor::restartSambaService()
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.restartSambaService
    return parent()->restartSambaService();
}

bool UserShareAdaptor::setUserSharePassword(const QString &username, const QString &passward)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.setUserSharePassword
    return parent()->setUserSharePassword(username, passward);
}

