/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../../plugins/desktop/ddplugin-dbusregister/devicemanagerdbus.h -c DeviceManagerAdaptor -l DeviceManagerDBus -a ../../plugins/desktop/ddplugin-dbusregister/dbus_adaptor/devicemanagerdbus_adaptor devicemanagerdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../../plugins/desktop/ddplugin-dbusregister/dbus_adaptor/devicemanagerdbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceManagerAdaptor
 */

DeviceManagerAdaptor::DeviceManagerAdaptor(DeviceManagerDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceManagerAdaptor::~DeviceManagerAdaptor()
{
    // destructor
}

void DeviceManagerAdaptor::DetachAllMountedDevices()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachAllMountedDevices
    parent()->DetachAllMountedDevices();
}

void DeviceManagerAdaptor::DetachBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachBlockDevice
    parent()->DetachBlockDevice(id);
}

void DeviceManagerAdaptor::DetachProtocolDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachProtocolDevice
    parent()->DetachProtocolDevice(id);
}

QStringList DeviceManagerAdaptor::GetBlockDevicesIdList(int opts)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.GetBlockDevicesIdList
    return parent()->GetBlockDevicesIdList(opts);
}

QStringList DeviceManagerAdaptor::GetProtocolDevicesIdList()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.GetProtocolDevicesIdList
    return parent()->GetProtocolDevicesIdList();
}

bool DeviceManagerAdaptor::IsMonotorWorking()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.IsMonotorWorking
    return parent()->IsMonotorWorking();
}

QVariantMap DeviceManagerAdaptor::QueryBlockDeviceInfo(const QString &id, bool reload)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryBlockDeviceInfo
    return parent()->QueryBlockDeviceInfo(id, reload);
}

QVariantMap DeviceManagerAdaptor::QueryProtocolDeviceInfo(const QString &id, bool reload)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryProtocolDeviceInfo
    return parent()->QueryProtocolDeviceInfo(id, reload);
}

