/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../../plugins/server/dfmplugin-interfaces/devicemanagerdbus.h -c DeviceManagerAdaptor -l DeviceManagerDBus -a ../../plugins/server/dfmplugin-interfaces/dbus_adaptor/devicemanagerdbus_adaptor devicemanagerdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../../plugins/server/dfmplugin-interfaces/dbus_adaptor/devicemanagerdbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceManagerAdaptor
 */

DeviceManagerAdaptor::DeviceManagerAdaptor(DeviceManagerDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceManagerAdaptor::~DeviceManagerAdaptor()
{
    // destructor
}

QStringList DeviceManagerAdaptor::BlockDevicesIdList()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.BlockDevicesIdList
    return parent()->BlockDevicesIdList();
}

void DeviceManagerAdaptor::EjectAllDevices()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.EjectAllDevices
    parent()->EjectAllDevices();
}

void DeviceManagerAdaptor::EjectDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.EjectDevice
    parent()->EjectDevice(id);
}

bool DeviceManagerAdaptor::IsMonotorWorking()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.IsMonotorWorking
    return parent()->IsMonotorWorking();
}

QStringList DeviceManagerAdaptor::ProtolcolDevicesIdList()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.ProtolcolDevicesIdList
    return parent()->ProtolcolDevicesIdList();
}

QString DeviceManagerAdaptor::QueryBlockDeviceInfo(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryBlockDeviceInfo
    return parent()->QueryBlockDeviceInfo(id);
}

QString DeviceManagerAdaptor::QueryProtocolDeviceInfo(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryProtocolDeviceInfo
    return parent()->QueryProtocolDeviceInfo(id);
}

