#!/bin/bash
#shell name: dde-property-dialog.sh
#description: reuqest show files's or folders's property dialog. 
#usage: just use it in bash like dde-property-dialog path1 path2 ...
dde-file-manager -d -p "$@";