/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ./sharecontroldbus.h -c ShareControlAdapter -l ShareControlDBus -a dbusadapter/sharecontrol_adapter sharecontroldbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadapter/sharecontrol_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ShareControlAdapter
 */

ShareControlAdapter::ShareControlAdapter(ShareControlDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ShareControlAdapter::~ShareControlAdapter()
{
    // destructor
}

bool ShareControlAdapter::CloseSmbShareByShareName(const QString &name, bool show)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.CloseSmbShareByShareName
    return parent()->CloseSmbShareByShareName(name, show);
}

bool ShareControlAdapter::EnableSmbServices()
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.EnableSmbServices
    return parent()->EnableSmbServices();
}

bool ShareControlAdapter::IsUserSharePasswordSet(const QString &username)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.IsUserSharePasswordSet
    return parent()->IsUserSharePasswordSet(username);
}

bool ShareControlAdapter::SetUserSharePassword(const QString &name, const QString &passwd)
{
    // handle method call com.deepin.filemanager.daemon.UserShareManager.SetUserSharePassword
    return parent()->SetUserSharePassword(name, passwd);
}

