# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-file-manager.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-file-manager.spec
    - .packit.yaml

upstream_package_name: dde-file-manager
# downstream (Fedora) RPM package name
downstream_package_name: deepin-file-manager

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-file-manager.spec"
