/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../tagdbus.h -c TagDBusAdaptor -l TagDBus -a dbus_adaptor/tagdbus_adaptor org.deepin.filemanager.tag.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TAGDBUS_ADAPTOR_H
#define TAGDBUS_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "../tagdbus.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.filemanager.Tag
 */
class TagDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.filemanager.Tag")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.filemanager.Tag\">\n"
"    <signal name=\"NewTagsAdded\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"tags\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"TagsDeleted\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"tags\"/>\n"
"    </signal>\n"
"    <signal name=\"TagColorChanged\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"oldAndNew\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"TagNameChanged\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"oldAndNew\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"FilesTagged\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"fileAndTags\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"FilesUntagged\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"fileAndTags\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <method name=\"Query\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Query\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"Insert\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"value\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <method name=\"Insert\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"Delete\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"value\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <method name=\"Delete\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"Update\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"value\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <method name=\"Update\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"CanTagFile\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"    </method>\n"
"    <method name=\"LastError\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TagDBusAdaptor(TagDBus *parent);
    virtual ~TagDBusAdaptor();

    inline TagDBus *parent() const
    { return static_cast<TagDBus *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool CanTagFile(const QString &filePath);
    bool Delete(uint type);
    bool Delete(uint type, const QVariantMap &value);
    bool Insert(uint type);
    bool Insert(uint type, const QVariantMap &value);
    QString LastError();
    QDBusVariant Query(uint type);
    QDBusVariant Query(uint type, const QStringList &value);
    bool Update(uint type);
    bool Update(uint type, const QVariantMap &value);
Q_SIGNALS: // SIGNALS
    void FilesTagged(const QVariantMap &fileAndTags);
    void FilesUntagged(const QVariantMap &fileAndTags);
    void NewTagsAdded(const QVariantMap &tags);
    void TagColorChanged(const QVariantMap &oldAndNew);
    void TagNameChanged(const QVariantMap &oldAndNew);
    void TagsDeleted(const QStringList &tags);
};

#endif
