/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i fileoperationjob/createtemplatefilejob.h -c CreateTemplateFileAdaptor -l CreateTemplateFileJob -a dbusadaptor/createtemplatefilejob_adaptor createtemplatefilejob.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor/createtemplatefilejob_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CreateTemplateFileAdaptor
 */

CreateTemplateFileAdaptor::CreateTemplateFileAdaptor(CreateTemplateFileJob *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CreateTemplateFileAdaptor::~CreateTemplateFileAdaptor()
{
    // destructor
}

void CreateTemplateFileAdaptor::Execute()
{
    // handle method call com.deepin.filemanager.daemon.CreateTemplateFileJob.Execute
    parent()->Execute();
}

