/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../mountcontroldbus.h -c MountControlAdapter -l MountControlDBus -a mountcontrol_adapter ../mountcontroldbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mountcontrol_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MountControlAdapter
 */

MountControlAdapter::MountControlAdapter(MountControlDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MountControlAdapter::~MountControlAdapter()
{
    // destructor
}

QVariantMap MountControlAdapter::Mount(const QString &path, const QVariantMap &opts)
{
    // handle method call com.deepin.filemanager.daemon.MountControl.Mount
    return parent()->Mount(path, opts);
}

QVariantMap MountControlAdapter::Unmount(const QString &path, const QVariantMap &opts)
{
    // handle method call com.deepin.filemanager.daemon.MountControl.Unmount
    return parent()->Unmount(path, opts);
}

