// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SERVICE_OPTICALSHARE_GLOBAL_H
#define SERVICE_OPTICALSHARE_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>
#include <dfm-base/dbusservice/global_server_defines.h>

#define SERVICEOPTICALSHARE_NAMESPACE service_opticalshare
#define SERVICEOPTICALSHARE_BEGIN_NAMESPACE namespace SERVICEOPTICALSHARE_NAMESPACE {
#define SERVICEOPTICALSHARE_END_NAMESPACE }
#define SERVICEOPTICALSHARE_USE_NAMESPACE using namespace SERVICEOPTICALSHARE_NAMESPACE;

SERVICEOPTICALSHARE_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(SERVICEOPTICALSHARE_NAMESPACE)
SERVICEOPTICALSHARE_END_NAMESPACE

#endif   // SERVICE_OPTICALSHARE_GLOBAL_H
