/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p soundeffect_interface.h:soundeffect_interface.cpp -c SoundEffectInterface soundeffect.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SOUNDEFFECT_INTERFACE_H_1469004792
#define SOUNDEFFECT_INTERFACE_H_1469004792

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.daemon.SoundEffect
 */
class SoundEffectInterface: public QDBusAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticServerPath()
    { return "com.deepin.daemon.SoundEffect"; }
    static inline const char *staticInterfacePath()
    { return "/com/deepin/daemon/SoundEffect"; }
    static inline const char *staticInterfaceName()
    { return "com.deepin.daemon.SoundEffect"; }

public:
    SoundEffectInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~SoundEffectInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> PlaySystemSound(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("PlaySystemSound"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
