#!/bin/bash

# SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0-or-later

start_time=$(date "+%Y-%m-%d %H:%M:%S.%3N")
echo -e "\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> started mounting ulnfs at [${start_time}]"
echo "dfm_INFO: user: $USER, uid: `id -u`, home: $HOME"

query_dconfig="dde-dconfig --get -a org.deepin.dde.file-manager -r org.deepin.dde.file-manager -k "
# obtain the config of ulnfs mount enable 
ulnfs_enable=`$query_dconfig dfm.mount.lnfs`
echo "dfm_INFO: ulnfs mount status: $ulnfs_enable"

if [ "$ulnfs_enable" == "true" ]; then
    default_paths=("$HOME")
    echo "dfm_INFO: default mount paths: $default_paths"
    gdbus call -y \
        -d com.deepin.filemanager.daemon \
        -o /com/deepin/filemanager/daemon/MountControl \
        -m com.deepin.filemanager.daemon.MountControl.Mount \
        "${default_paths}" \
        "{'fsType': <'ulnfs'>}" \
        -t 1    

    step_time=$(date "+%Y-%m-%d %H:%M:%S.%3N")
    echo -e "dfm_INFO: finished mount ${path} at [${step_time}]\n"    
fi

end_time=$(date "+%Y-%m-%d %H:%M:%S.%3N")
echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< finished mounting ulnfs at [${end_time}]\n"
