/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c FileOperationAdaptor -a fileoperation_adaptor -l FileOperation fileoperation.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "fileoperation_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FileOperationAdaptor
 */

FileOperationAdaptor::FileOperationAdaptor(FileOperation *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FileOperationAdaptor::~FileOperationAdaptor()
{
    // destructor
}

QDBusVariant FileOperationAdaptor::NewRenameJob(const QString &oldFile, const QString &newFile)
{
    // handle method call com.deepin.filemanager.daemon.Operations.NewRenameJob
    return parent()->NewRenameJob(oldFile, newFile);
}

QString FileOperationAdaptor::test(const QString &oldFile, const QString &newFile, QDBusObjectPath &result2, bool &result3)
{
    // handle method call com.deepin.filemanager.daemon.Operations.test
    return parent()->test(oldFile, newFile, result2, result3);
}

