/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c FileOperationAdaptor -a fileoperation_adaptor -l FileOperation fileoperation.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FILEOPERATION_ADAPTOR_H_1470300087
#define FILEOPERATION_ADAPTOR_H_1470300087

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.daemon.Operations
 */
class FileOperationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.daemon.Operations")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.daemon.Operations\">\n"
"    <method name=\"NewRenameJob\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"oldFile\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"newFile\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"test\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"oldFile\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"newFile\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result1\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"result2\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result3\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    FileOperationAdaptor(FileOperation *parent);
    virtual ~FileOperationAdaptor();

    inline FileOperation *parent() const
    { return static_cast<FileOperation *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusVariant NewRenameJob(const QString &oldFile, const QString &newFile);
    QString test(const QString &oldFile, const QString &newFile, QDBusObjectPath &result2, bool &result3);
Q_SIGNALS: // SIGNALS
};

#endif
