/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c RenameJobAdaptor -a renamejob_adaptor renamejob.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef RENAMEJOB_ADAPTOR_H_1470204189
#define RENAMEJOB_ADAPTOR_H_1470204189

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.daemon.RenameJob
 */
class RenameJobAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.daemon.RenameJob")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.daemon.RenameJob\">\n"
"    <method name=\"Execute\"/>\n"
"    <signal name=\"Done\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    RenameJobAdaptor(QObject *parent);
    virtual ~RenameJobAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Execute();
Q_SIGNALS: // SIGNALS
    void Done(const QString &in0);
};

#endif
