/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c MoveJobInterface -p dbusinterface/movejob_interface movejob.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusinterface/movejob_interface.h"

/*
 * Implementation of interface class MoveJobInterface
 */

MoveJobInterface::MoveJobInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MoveJobInterface::~MoveJobInterface()
{
}

