// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef MERGEDDESKTOP_COMMON_P_H
#define MERGEDDESKTOP_COMMON_P_H

#define VIRTUALENTRY_FOLDER "entry/"
#define VIRTUALENTRY_PATH "/" VIRTUALENTRY_FOLDER

#define VIRTUALFOLDER_FOLDER "folder/"
#define VIRTUALFOLDER_PATH "/" VIRTUALFOLDER_FOLDER

#define MERGEDDESKTOP_FOLDER "mergeddesktop/"
#define MERGEDDESKTOP_PATH "/" MERGEDDESKTOP_FOLDER

#endif // MERGEDDESKTOP_COMMON_P_H
