Dtk--Widget--DTitlebar {
    background: #101010;
}

Dtk--Widget--DTitlebar[transparent=true] {
    background: transparent;
}

Dtk--Widget--DWindowCloseButton {
    qproperty-normalPic: url(:/images/dark/images/window/close_normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/window/close_hover.svg);
    qproperty-pressPic: url(:/images/dark/images/window/close_press.svg);
    padding-right: 6px;
}

#DTitlebarDWindowQuitFullscreenButton {
    qproperty-normalPic: url(:/images/dark/images/window/quit_fullscreen_normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/window/quit_fullscreen_hover.svg);
    qproperty-pressPic: url(:/images/dark/images/window/quit_fullscreen_press.svg);
    padding-right: 6px;
}
