/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.filemanager.filedialogmanager.xml -i filedialogmanagerdbus.h -a filedialogmanager_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "filedialogmanager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FiledialogmanagerAdaptor
 */

FiledialogmanagerAdaptor::FiledialogmanagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FiledialogmanagerAdaptor::~FiledialogmanagerAdaptor()
{
    // destructor
}

bool FiledialogmanagerAdaptor::canUseFileChooserDialog(const QString &group, const QString &executableFileName)
{
    // handle method call com.deepin.filemanager.filedialogmanager.canUseFileChooserDialog
    bool ok;
    QMetaObject::invokeMethod(parent(), "canUseFileChooserDialog", Q_RETURN_ARG(bool, ok), Q_ARG(QString, group), Q_ARG(QString, executableFileName));
    return ok;
}

QDBusObjectPath FiledialogmanagerAdaptor::createDialog(const QString &key)
{
    // handle method call com.deepin.filemanager.filedialogmanager.createDialog
    QDBusObjectPath path;
    QMetaObject::invokeMethod(parent(), "createDialog", Q_RETURN_ARG(QDBusObjectPath, path), Q_ARG(QString, key));
    return path;
}

void FiledialogmanagerAdaptor::destroyDialog(const QDBusObjectPath &path)
{
    // handle method call com.deepin.filemanager.filedialogmanager.destroyDialog
    QMetaObject::invokeMethod(parent(), "destroyDialog", Q_ARG(QDBusObjectPath, path));
}

QList<QDBusObjectPath> FiledialogmanagerAdaptor::dialogs()
{
    // handle method call com.deepin.filemanager.filedialogmanager.dialogs
    QList<QDBusObjectPath> dialogObjectList;
    QMetaObject::invokeMethod(parent(), "dialogs", Q_RETURN_ARG(QList<QDBusObjectPath>, dialogObjectList));
    return dialogObjectList;
}

QString FiledialogmanagerAdaptor::errorString()
{
    // handle method call com.deepin.filemanager.filedialogmanager.errorString
    QString error;
    QMetaObject::invokeMethod(parent(), "errorString", Q_RETURN_ARG(QString, error));
    return error;
}

QStringList FiledialogmanagerAdaptor::globPatternsForMime(const QString &mime)
{
    // handle method call com.deepin.filemanager.filedialogmanager.globPatternsForMime
    QStringList patterns;
    QMetaObject::invokeMethod(parent(), "globPatternsForMime", Q_RETURN_ARG(QStringList, patterns), Q_ARG(QString, mime));
    return patterns;
}

bool FiledialogmanagerAdaptor::isUseFileChooserDialog()
{
    // handle method call com.deepin.filemanager.filedialogmanager.isUseFileChooserDialog
    bool ok;
    QMetaObject::invokeMethod(parent(), "isUseFileChooserDialog", Q_RETURN_ARG(bool, ok));
    return ok;
}

QStringList FiledialogmanagerAdaptor::monitorFiles()
{
    // handle method call com.deepin.filemanager.filedialogmanager.monitorFiles
    QStringList files;
    QMetaObject::invokeMethod(parent(), "monitorFiles", Q_RETURN_ARG(QStringList, files));
    return files;
}

void FiledialogmanagerAdaptor::showBluetoothTransDialog(const QString &id, const QStringList &URIs)
{
    // handle method call com.deepin.filemanager.filedialogmanager.showBluetoothTransDialog
    QMetaObject::invokeMethod(parent(), "showBluetoothTransDialog", Q_ARG(QString, id), Q_ARG(QStringList, URIs));
}

