/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p licenseInterface.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "licenceInterface.h"
/*
 * Implementation of interface class ComDeepinLicenseInterface
 */

ComDeepinLicenseInterface::ComDeepinLicenseInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinLicenseInterface::~ComDeepinLicenseInterface()
{
}
