// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SERVERPLUGIN_GRANDSEARCHDAEMON_GLOBAL_H
#define SERVERPLUGIN_GRANDSEARCHDAEMON_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define SERVERPGRANDSEARCH_NAMESPACE serverplugin_grandsearchdaemon

#define SERVERPGRANDSEARCH_NAMESPACE_BEGIN_NAMESPACE namespace SERVERPGRANDSEARCH_NAMESPACE {
#define SERVERPGRANDSEARCH_NAMESPACE_END_NAMESPACE }
#define SERVERPGRANDSEARCH_NAMESPACE_USE_NAMESPACE using namespace SERVERPGRANDSEARCH_NAMESPACE;

SERVERPGRANDSEARCH_NAMESPACE_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(SERVERPGRANDSEARCH_NAMESPACE)
SERVERPGRANDSEARCH_NAMESPACE_END_NAMESPACE

#endif   // SERVERPLUGIN_GRANDSEARCHDAEMON_GLOBAL_H
