// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DAEMONPLUGIN_OPTICALSHARE_GLOBAL_H
#define DAEMONPLUGIN_OPTICALSHARE_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DAEMONPOPTICALSHARE_NAMESPACE daemonplugin_opticalshare

#define DAEMONPOPTICALSHARE_BEGIN_NAMESPACE namespace DAEMONPOPTICALSHARE_NAMESPACE {
#define DAEMONPOPTICALSHARE_END_NAMESPACE }
#define DAEMONPOPTICALSHARE_USE_NAMESPACE using namespace DAEMONPOPTICALSHARE_NAMESPACE;

DAEMONPOPTICALSHARE_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(DAEMONPOPTICALSHARE_NAMESPACE)
DAEMONPOPTICALSHARE_END_NAMESPACE

#endif   // DAEMONPLUGIN_OPTICALSHARE_GLOBAL_H
