// SPDX-FileCopyrightText: 2025 - 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef EXTRACTOR_PLUGIN_GLOBAL_H
#define EXTRACTOR_PLUGIN_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define EXTRACTOR_PLUGIN_NAMESPACE extractor_plugin
#define EXTRACTOR_PLUGIN_BEGIN_NAMESPACE namespace EXTRACTOR_PLUGIN_NAMESPACE {
#define EXTRACTOR_PLUGIN_END_NAMESPACE }
#define EXTRACTOR_PLUGIN_USE_NAMESPACE using namespace EXTRACTOR_PLUGIN_NAMESPACE;

EXTRACTOR_PLUGIN_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(EXTRACTOR_PLUGIN_NAMESPACE)
EXTRACTOR_PLUGIN_END_NAMESPACE

#endif   // EXTRACTOR_PLUGIN_GLOBAL_H
