usr/lib/*/libdde-file-manager.so.*
usr/share/dde-file-manager/translations/*.qm
usr/share/dde-file-manager/templates/*
usr/share/dde-file-manager/mimetypes/*
usr/share/dde-file-manager/mimetypeassociations/*
usr/share/dde-file-manager/extensions/appEntry/.readme
usr/share/icons/*

usr/lib/*/dde-file-manager/plugins/*
usr/lib/*/dde-file-manager/tools/*

usr/share/glib-2.0/schemas/*.filemanager.gschema.xml

usr/share/deepin/dde-file-manager/oem-menuextensions/.readme

usr/share/applications/context-menus/.readme
