#!/bin/bash

arch=$(dpkg --print-architecture)
if [ ${arch} == 'sw_64' ];then
	if [ -f /etc/xdg/autostart/dde-file-manager-autostart.desktop ];then
		rm -f /etc/xdg/autostart/dde-file-manager-autostart.desktop || true
	fi
fi

if [ ${arch} == 'mips64el' ];then
	if [ -f /etc/xdg/autostart/dde-file-manager-autostart.desktop ];then
		rm -f /etc/xdg/autostart/dde-file-manager-autostart.desktop || true
	fi
fi
