/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusMonitor -p dbusmonitor1 org.deepin.dde.Display1.Monitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusmonitor1.h"

/*
 * Implementation of interface class DBusMonitor
 */

DBusMonitor::DBusMonitor(const QString &objectPath, QObject *parent)
    : QDBusAbstractInterface(staticServiceName(), objectPath, staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
    QDBusConnection::sessionBus().connect(this->service(), this->path(), "org.freedesktop.DBus.Properties",  "PropertiesChanged","sa{sv}as", this, SLOT(__propertyChanged__(QDBusMessage)));
}

DBusMonitor::~DBusMonitor()
{
    QDBusConnection::sessionBus().disconnect(
                service(), path(), "org.freedesktop.DBus.Properties",
                "PropertiesChanged",  "sa{sv}as", this, SLOT(propertyChanged(QDBusMessage)));
}

QRect DBusMonitor::rect() const
{
    return QRect(x(),y(),width(),height());
}
