// SPDX-FileCopyrightText: 2022 - 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DDPLUGIN_WALLPAPERSETTING_GLOBAL_H
#define DDPLUGIN_WALLPAPERSETTING_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DDP_WALLPAERSETTING_NAMESPACE ddplugin_wallpapersetting

#define DDP_WALLPAERSETTING_BEGIN_NAMESPACE namespace DDP_WALLPAERSETTING_NAMESPACE {
#define DDP_WALLPAERSETTING_END_NAMESPACE }
#define DDP_WALLPAERSETTING_USE_NAMESPACE using namespace DDP_WALLPAERSETTING_NAMESPACE;

DDP_WALLPAERSETTING_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(DDP_WALLPAERSETTING_NAMESPACE)
DDP_WALLPAERSETTING_END_NAMESPACE

#endif   // DDPLUGIN_WALLPAPERSETTING_GLOBAL_H
