/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p clipboard_interface.h:clipboard_interface.cpp -c ClipboardInterface /home/djf/workspace/github/QtDBusXmlTool/clipboard.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CLIPBOARD_INTERFACE_H_1437455851
#define CLIPBOARD_INTERFACE_H_1437455851

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.filemanager.Backend.Clipboard
 */
class ClipboardInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.filemanager.Backend.Clipboard"; }

public:
    ClipboardInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ClipboardInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> CopyToClipboard(const QStringList &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("CopyToClipboard"), argumentList);
    }

    inline QDBusPendingReply<> CutToClipboard(const QStringList &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("CutToClipboard"), argumentList);
    }

    inline QDBusPendingReply<> EmitPaste(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("EmitPaste"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void RequestPaste(const QString &in0, const QStringList &in1, const QString &in2);
};

#endif
