/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p clipboard_interface.h:clipboard_interface.cpp -c ClipboardInterface /home/djf/workspace/github/QtDBusXmlTool/clipboard.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "clipboard_interface.h"

/*
 * Implementation of interface class ClipboardInterface
 */

ClipboardInterface::ClipboardInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ClipboardInterface::~ClipboardInterface()
{
}

