/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p filelistjob_interface.h:filelistjob_interface.cpp -c FileListJobInterface filelistjob.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef FILELISTJOB_INTERFACE_H_1436261514
#define FILELISTJOB_INTERFACE_H_1436261514

#include "dbustype.h"
#include <QDBusMetaType>
#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.filemanager.Backend.Operations.ListJob
 */
class FileListJobInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.filemanager.Backend.Operations.ListJob"; }

public:
    FileListJobInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~FileListJobInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Abort()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Abort"), argumentList);
    }

    inline QDBusPendingReply<EntryInfoObjList> Execute()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Execute"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Aborted();
    void Done(const QString &in0);
    void EntryInfo(const QString &in0, const QString &in1, const QString &in2, const QString &in3, const QString &in4, qlonglong in5, ushort in6, bool in7, bool in8, bool in9, bool in10, bool in11, bool in12, bool in13, bool in14, bool in15);
    void ProcessedAmount(qlonglong in0, ushort in1);
};

#endif
