/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p filemonitorInstance_interface.h:filemonitorInstance_interface.cpp -c FileMonitorInstanceInterface /home/djf/workspace/github/QtDBusXmlTool/filemonitorInstance.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "filemonitorInstance_interface.h"

/*
 * Implementation of interface class FileMonitorInstanceInterface
 */

FileMonitorInstanceInterface::FileMonitorInstanceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FileMonitorInstanceInterface::~FileMonitorInstanceInterface()
{
}

