/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p monitormanager_interface.h:monitormanager_interface.cpp -c MonitorManagerInterface /home/djf/workspace/github/QtDBusXmlTool/monitormanager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "monitormanager_interface.h"

/*
 * Implementation of interface class MonitorManagerInterface
 */

MonitorManagerInterface::MonitorManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MonitorManagerInterface::~MonitorManagerInterface()
{
}

