/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p trashmonitor_interface.h:trashmonitor_interface.cpp -c TrashMonitorInterface trashmonitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef TRASHMONITOR_INTERFACE_H_1436253320
#define TRASHMONITOR_INTERFACE_H_1436253320

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.filemanager.Backend.TrashMonitor
 */
class TrashMonitorInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.filemanager.Backend.Monitor.TrashMonitor"; }

public:
    TrashMonitorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~TrashMonitorInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<uint> ItemCount()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ItemCount"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ItemCountChanged(uint in0);
};

#endif
