// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SERVERPLUGIN_TAGDAEMON_GLOBAL_H
#define SERVERPLUGIN_TAGDAEMON_GLOBAL_H

#define SERVERTAGDAEMON_NAMESPACE serverplugin_tagdaemon

#define SERVERTAGDAEMON_BEGIN_NAMESPACE namespace SERVERTAGDAEMON_NAMESPACE {
#define SERVERTAGDAEMON_END_NAMESPACE }
#define SERVERTAGDAEMON_USE_NAMESPACE using namespace SERVERTAGDAEMON_NAMESPACE;

SERVERTAGDAEMON_BEGIN_NAMESPACE

SERVERTAGDAEMON_END_NAMESPACE

#endif   // SERVERPLUGIN_TAGDAEMON_GLOBAL_H
