/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../../plugins/server/dfmsplugin-interfaces/devicemanagerdbus.h -c DeviceManagerAdaptor -l DeviceManagerDBus -a ../../plugins/server/dfmsplugin-interfaces/dbus_adaptor/devicemanagerdbus_adaptor devicemanagerdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../../plugins/server/dfmsplugin-interfaces/dbus_adaptor/devicemanagerdbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceManagerAdaptor
 */

DeviceManagerAdaptor::DeviceManagerAdaptor(DeviceManagerDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceManagerAdaptor::~DeviceManagerAdaptor()
{
    // destructor
}

void DeviceManagerAdaptor::DetachAllMountedDevices()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachAllMountedDevices
    parent()->DetachAllMountedDevices();
}

void DeviceManagerAdaptor::DetachAllMountedDevicesForced()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachAllMountedDevicesForced
    parent()->DetachAllMountedDevicesForced();
}

void DeviceManagerAdaptor::DetachBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachBlockDevice
    parent()->DetachBlockDevice(id);
}

void DeviceManagerAdaptor::DetachBlockDeviceForced(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachBlockDeviceForced
    parent()->DetachBlockDeviceForced(id);
}

void DeviceManagerAdaptor::DetachProtocolDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.DetachProtocolDevice
    parent()->DetachProtocolDevice(id);
}

void DeviceManagerAdaptor::EjectBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.EjectBlockDevice
    parent()->EjectBlockDevice(id);
}

QStringList DeviceManagerAdaptor::GetBlockDevicesIdList(const QVariantMap &opts)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.GetBlockDevicesIdList
    return parent()->GetBlockDevicesIdList(opts);
}

QStringList DeviceManagerAdaptor::GetProtocolDevicesIdList()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.GetProtocolDevicesIdList
    return parent()->GetProtocolDevicesIdList();
}

bool DeviceManagerAdaptor::IsMonotorWorking()
{
    // handle method call com.deepin.filemanager.service.DeviceManager.IsMonotorWorking
    return parent()->IsMonotorWorking();
}

void DeviceManagerAdaptor::LockBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.LockBlockDevice
    parent()->LockBlockDevice(id);
}

QString DeviceManagerAdaptor::MountBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.MountBlockDevice
    return parent()->MountBlockDevice(id);
}

void DeviceManagerAdaptor::MountNetworkDevice(const QString &address, bool anonymous, const QVariantMap &opts)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.MountNetworkDevice
    parent()->MountNetworkDevice(address, anonymous, opts);
}

QString DeviceManagerAdaptor::MountProtocolDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.MountProtocolDevice
    return parent()->MountProtocolDevice(id);
}

void DeviceManagerAdaptor::PoweroffBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.PoweroffBlockDevice
    parent()->PoweroffBlockDevice(id);
}

QVariantMap DeviceManagerAdaptor::QueryBlockDeviceInfo(const QString &id, bool detail)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryBlockDeviceInfo
    return parent()->QueryBlockDeviceInfo(id, detail);
}

QVariantMap DeviceManagerAdaptor::QueryProtocolDeviceInfo(const QString &id, bool detail)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.QueryProtocolDeviceInfo
    return parent()->QueryProtocolDeviceInfo(id, detail);
}

void DeviceManagerAdaptor::SafelyRemoveBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.SafelyRemoveBlockDevice
    parent()->SafelyRemoveBlockDevice(id);
}

QString DeviceManagerAdaptor::UnlockBlockDevice(const QString &id, const QString &passwd)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.UnlockBlockDevice
    return parent()->UnlockBlockDevice(id, passwd);
}

void DeviceManagerAdaptor::UnmountBlockDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.UnmountBlockDevice
    parent()->UnmountBlockDevice(id);
}

void DeviceManagerAdaptor::UnmountBlockDeviceForced(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.UnmountBlockDeviceForced
    parent()->UnmountBlockDeviceForced(id);
}

void DeviceManagerAdaptor::UnmountProtocolDevice(const QString &id)
{
    // handle method call com.deepin.filemanager.service.DeviceManager.UnmountProtocolDevice
    parent()->UnmountProtocolDevice(id);
}

