/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c ConflictAdaptor -a conflictdaptor ./dde-desktop-conflict.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONFLICTDAPTOR_H_1452566596
#define CONFLICTDAPTOR_H_1452566596

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "../dbustype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.desktop.conflict
 */
class ConflictAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.desktop.conflict")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.desktop.conflict\">\n"
"    <method name=\"AskRetry\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"{ibs}\"/>\n"
"      <annotation value=\"ConflictInfo\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"AskDeleteConfirmation\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"AskDelete\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <arg direction=\"out\" type=\"{ibs}\"/>\n"
"      <annotation value=\"ConflictInfo\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"AskSkip\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <arg direction=\"out\" type=\"{ibs}\"/>\n"
"      <annotation value=\"ConflictInfo\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"ConflictDialog\">\n"
"      <arg direction=\"out\" type=\"{ibs}\"/>\n"
"      <annotation value=\"ConflictInfo\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <signal name=\"response\">\n"
"      <arg type=\"{ibs}\"/>\n"
"      <annotation value=\"ConflictInfo\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    static inline const char *staticServerPath()
    { return "com.deepin.dde.desktop"; }
    static inline const char *staticInterfacePath()
    { return "/com/deepin/dde/desktop/conflict"; }
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.desktop.conflict"; }
    ConflictAdaptor(QObject *parent);
    virtual ~ConflictAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    ConflictInfo AskDelete(const QString &in0, const QString &in1, const QString &in2, bool in3, bool in4);
    bool AskDeleteConfirmation(const QString &in0, const QString &in1, const QString &in2);
    ConflictInfo AskRetry(const QString &in0, const QString &in1, const QString &in2);
    ConflictInfo AskSkip(const QString &in0, const QString &in1, const QString &in2, bool in3, bool in4);
    ConflictInfo ConflictDialog();
Q_SIGNALS: // SIGNALS
    void response(ConflictInfo in0);
};

#endif
