/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c ConflictAdaptor -a conflictdaptor ./dde-desktop-conflict.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "conflictdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ConflictAdaptor
 */

ConflictAdaptor::ConflictAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor

    qRegisterMetaType<ConflictInfo>("ConflictInfo");
    qDBusRegisterMetaType<ConflictInfo>();
    setAutoRelaySignals(true);
}

ConflictAdaptor::~ConflictAdaptor()
{
    // destructor
}

ConflictInfo ConflictAdaptor::AskDelete(const QString &in0, const QString &in1, const QString &in2, bool in3, bool in4)
{
    // handle method call com.deepin.dde.Desktop.conflict.AskDelete
    ConflictInfo out0;
    QMetaObject::invokeMethod(parent(), "AskDelete", Q_RETURN_ARG(ConflictInfo, out0), Q_ARG(QString, in0), Q_ARG(QString, in1), Q_ARG(QString, in2), Q_ARG(bool, in3), Q_ARG(bool, in4));
    return out0;
}

bool ConflictAdaptor::AskDeleteConfirmation(const QString &in0, const QString &in1, const QString &in2)
{
    // handle method call com.deepin.dde.Desktop.conflict.AskDeleteConfirmation
    bool out0;
    QMetaObject::invokeMethod(parent(), "AskDeleteConfirmation", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0), Q_ARG(QString, in1), Q_ARG(QString, in2));
    return out0;
}

ConflictInfo ConflictAdaptor::AskRetry(const QString &in0, const QString &in1, const QString &in2)
{
    // handle method call com.deepin.dde.Desktop.conflict.AskRetry
    ConflictInfo out0;
    QMetaObject::invokeMethod(parent(), "AskRetry", Q_RETURN_ARG(ConflictInfo, out0), Q_ARG(QString, in0), Q_ARG(QString, in1), Q_ARG(QString, in2));
    return out0;
}

ConflictInfo ConflictAdaptor::AskSkip(const QString &in0, const QString &in1, const QString &in2, bool in3, bool in4)
{
    // handle method call com.deepin.dde.Desktop.conflict.AskSkip
    ConflictInfo out0;
    QMetaObject::invokeMethod(parent(), "AskSkip", Q_RETURN_ARG(ConflictInfo, out0), Q_ARG(QString, in0), Q_ARG(QString, in1), Q_ARG(QString, in2), Q_ARG(bool, in3), Q_ARG(bool, in4));
    return out0;
}

ConflictInfo ConflictAdaptor::ConflictDialog()
{
    // handle method call com.deepin.dde.Desktop.conflict.ConflictDialog
    ConflictInfo out0;
    QMetaObject::invokeMethod(parent(), "ConflictDialog", Q_RETURN_ARG(ConflictInfo, out0));
    return out0;
}

