/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c DesktopAdaptor -a desktopadaptor dde-desktop.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "desktopadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DesktopAdaptor
 */

DesktopAdaptor::DesktopAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DesktopAdaptor::~DesktopAdaptor()
{
    // destructor
}

void DesktopAdaptor::exit()
{
    // handle method call com.deepin.dde.Desktop.exit
    QMetaObject::invokeMethod(parent(), "exit");
}

void DesktopAdaptor::hide()
{
    // handle method call com.deepin.dde.Desktop.hide
    QMetaObject::invokeMethod(parent(), "hide");
}

void DesktopAdaptor::show()
{
    // handle method call com.deepin.dde.Desktop.show
    QMetaObject::invokeMethod(parent(), "show");
}

void DesktopAdaptor::toggle()
{
    // handle method call com.deepin.dde.Desktop.toggle
    QMetaObject::invokeMethod(parent(), "toggle");
}

