/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c DesktopAdaptor -a desktopadaptor dde-desktop.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DESKTOPADAPTOR_H_1442197124
#define DESKTOPADAPTOR_H_1442197124

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.Desktop
 */
class DesktopAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.Desktop")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.Desktop\">\n"
"    <method name=\"exit\"/>\n"
"    <method name=\"show\"/>\n"
"    <method name=\"hide\"/>\n"
"    <method name=\"toggle\"/>\n"
"    <signal name=\"closed\"/>\n"
"    <signal name=\"shown\"/>\n"
"  </interface>\n"
        "")
public:
    DesktopAdaptor(QObject *parent);
    virtual ~DesktopAdaptor();

    static inline const char *staticServerPath()
    { return "com.deepin.dde.desktop"; }
    static inline const char *staticInterfacePath()
    { return "/com/deepin/dde/desktop"; }
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.Desktop"; }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void exit();
    void hide();
    void show();
    void toggle();
Q_SIGNALS: // SIGNALS
    void closed();
    void shown();
};

#endif
