// SPDX-FileCopyrightText: 2022 - 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DAEMONPLUGIN_SHARECONTROL_GLOBAL_H
#define DAEMONPLUGIN_SHARECONTROL_GLOBAL_H

#define DAEMONPSHARECONTROL_NAMESPACE daemonplugin_sharecontrol
#define DAEMONPSHARECONTROL_BEGIN_NAMESPACE namespace DAEMONPSHARECONTROL_NAMESPACE {
#define DAEMONPSHARECONTROL_END_NAMESPACE }
#define DAEMONPSHARECONTROL_USE_NAMESPACE using namespace DAEMONPSHARECONTROL_NAMESPACE;

#endif   // DAEMONPLUGIN_SHARECONTROL_GLOBAL_H
