/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DeviceManagerInterface -p dbus_interface/devicemanagerdbus_interface devicemanagerdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DEVICEMANAGERDBUS_INTERFACE_H
#define DEVICEMANAGERDBUS_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.deepin.filemanager.service.DeviceManager
 */
class DeviceManagerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.deepin.filemanager.service.DeviceManager"; }

public:
    DeviceManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~DeviceManagerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> DetachAllMountedDevices()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("DetachAllMountedDevices"), argumentList);
    }

    inline QDBusPendingReply<> DetachBlockDevice(const QString &id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id);
        return asyncCallWithArgumentList(QStringLiteral("DetachBlockDevice"), argumentList);
    }

    inline QDBusPendingReply<> DetachProtocolDevice(const QString &id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id);
        return asyncCallWithArgumentList(QStringLiteral("DetachProtocolDevice"), argumentList);
    }

    inline QDBusPendingReply<QStringList> GetBlockDevicesIdList(int opts)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(opts);
        return asyncCallWithArgumentList(QStringLiteral("GetBlockDevicesIdList"), argumentList);
    }

    inline QDBusPendingReply<QStringList> GetProtocolDevicesIdList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetProtocolDevicesIdList"), argumentList);
    }

    inline QDBusPendingReply<bool> IsMonotorWorking()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("IsMonotorWorking"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> QueryBlockDeviceInfo(const QString &id, bool reload)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(reload);
        return asyncCallWithArgumentList(QStringLiteral("QueryBlockDeviceInfo"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> QueryProtocolDeviceInfo(const QString &id, bool reload)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(reload);
        return asyncCallWithArgumentList(QStringLiteral("QueryProtocolDeviceInfo"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void BlockDeviceAdded(const QString &id);
    void BlockDeviceFilesystemAdded(const QString &id);
    void BlockDeviceFilesystemRemoved(const QString &id);
    void BlockDeviceLocked(const QString &id);
    void BlockDeviceMounted(const QString &id, const QString &mountPoint);
    void BlockDevicePropertyChanged(const QString &id, const QString &property, const QDBusVariant &value);
    void BlockDeviceRemoved(const QString &id);
    void BlockDeviceUnlocked(const QString &id, const QString &clearDeviceId);
    void BlockDeviceUnmounted(const QString &id);
    void BlockDriveAdded();
    void BlockDriveRemoved();
    void NotifyDeviceBusy(int action);
    void ProtocolDeviceAdded(const QString &id);
    void ProtocolDeviceMounted(const QString &id, const QString &mountPoint);
    void ProtocolDeviceRemoved(const QString &id);
    void ProtocolDeviceUnmounted(const QString &id);
    void SizeUsedChanged(const QString &id, qlonglong total, qlonglong free);
};

namespace org {
  namespace deepin {
    namespace filemanager {
      namespace service {
        typedef ::DeviceManagerInterface DeviceManager;
      }
    }
  }
}
#endif
