/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c OperationsStackManagerInterface -p dbus_interface/operationsstackmanagerdbus_interface operationsstackmanagerdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include <dfm-base/dbusservice/dbus_interface/operationsstackmanagerdbus_interface.h>

/*
 * Implementation of interface class OperationsStackManagerInterface
 */

OperationsStackManagerInterface::OperationsStackManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OperationsStackManagerInterface::~OperationsStackManagerInterface()
{
}
