// SPDX-FileCopyrightText: 2022 - 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DAEMONPLUGIN_ANYTHING_GLOBAL_H
#define DAEMONPLUGIN_ANYTHING_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DAEMONPANYTHING_NAMESPACE daemonplugin_anything
#define DAEMONPANYTHING_BEGIN_NAMESPACE namespace DAEMONPANYTHING_NAMESPACE {
#define DAEMONPANYTHING_END_NAMESPACE }
#define DAEMONPANYTHING_USE_NAMESPACE using namespace DAEMONPANYTHING_NAMESPACE;

DAEMONPANYTHING_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(DAEMONPANYTHING_NAMESPACE)
DAEMONPANYTHING_END_NAMESPACE

#endif   // DAEMONPLUGIN_ANYTHING_GLOBAL_H
