// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SERVERPLUGIN_FILEMANAGER1_GLOBAL_H
#define SERVERPLUGIN_FILEMANAGER1_GLOBAL_H

#define SERVERFILEMANAGER1_NAMESPACE serverplugin_filemanager1

#define SERVERFILEMANAGER1_BEGIN_NAMESPACE namespace SERVERFILEMANAGER1_NAMESPACE {
#define SERVERFILEMANAGER1_END_NAMESPACE }
#define SERVERFILEMANAGER1_USE_NAMESPACE using namespace SERVERFILEMANAGER1_NAMESPACE;

#endif   // SERVERPLUGIN_FILEMANAGER1_GLOBAL_H
