/*
 * Copyright (C) 2021 Uniontech Software Technology Co., Ltd.
 *
 * Author:     xushitong<xushitong@uniontech.com>
 *
 * Maintainer: max-lv<lvwujun@uniontech.com>
 *             lanxuesong<lanxuesong@uniontech.com>
 *             zhangsheng<zhangsheng@uniontech.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <DSettings>

/*!
 * \brief global_setting_template_manully_trans
 * if there is any sentence that cannot be generated by dtksettings, write it here
 * to make sure it can be translated
 *
 * for now, option like:
 *
 *  "items": {
 *      "values": ["a"],
 *      "keys": ["a"]
 *  }
 *
 *  the writtings in items.values cannot be generated automatically
 */

void global_setting_template_manully_trans()
{
    auto base_default_view_icon_modeValue1 = QObject::tr("Icon");
    auto base_default_view_icon_modeValue2 = QObject::tr("List");

    auto base_new_tab_windows_new_tab_pathValue1 = QObject::tr("Current Directory");

    Q_UNUSED(base_default_view_icon_modeValue1);
    Q_UNUSED(base_default_view_icon_modeValue2);
    Q_UNUSED(base_new_tab_windows_new_tab_pathValue1);
}
